name: Hot plug cameras

on:
  workflow_call:
    inputs:
      platform:
        required: false
        type: string
      dt-overlay-options:
        required: true
        type: string

jobs:
  camera-hotplug:
    runs-on: [self-hosted, linux, ARM64, "${{ inputs.platform }}"]
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build dtbocfg
        run: |
          cd ./scripts/common/hotplug/dtbocfg/
          make
          ls -l ./dtbocfg.ko
          sudo rmmod dtbocfg || true
          sudo insmod ./dtbocfg.ko || true
          lsmod | grep dtbocfg
      - name: Hotplug
        run: |
          ./scripts/common/hotplug/camera-hotplug.sh ${{ inputs.dt-overlay-options }}

  post-hotplug-checks:
    runs-on: [self-hosted, linux, ARM64, "${{ inputs.platform }}"]
    needs: camera-hotplug
    timeout-minutes: 3
    steps:
      - run: |
          find /proc/device-tree/ -name "*isx*" || find /proc/device-tree/ -name "*imx*"
          find /proc/device-tree/ -name "*max9295*"
          find /proc/device-tree/ -name "*max9296*"
          find /proc/device-tree/ -name "*fpga*"
          ls -l /dev/video*
          ls -l /dev/v4l-*
          ls -l /dev/media*
          ls -l /dev/gmsl/
          for media_device in $(find /dev/ -type c -name "media*"); do
            media-ctl -d "${media_device}" -p
          done
          for video_device in $(find /dev/ -type c -name "video*"); do
            v4l2-ctl -d "${video_device}" --all
          done
