name: ROSCube RQX-58G C C1x2 C2x2 C1x2 C2x2

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-drivers:
    uses: ./.github/workflows/build-drivers-hosted.yaml
    with:
      platform: rqx58g-c

  camera-hotplug:
    needs: build-drivers
    uses: ./.github/workflows/camera-hotplug-hosted.yaml
    with:
      platform: rqx58g-c
      dt-overlay-options: roscube R32.6.1 -2 C1 -2 C2 -2 C1 -2 C2

  test-camera-0:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-isx021-cam1
      gstreamer-options: 'video/x-raw, width=1920, height=1280, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c1-0

  test-camera-1:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-isx021-cam2
      gstreamer-options: 'video/x-raw, width=1920, height=1280, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c1-1

  test-camera-2:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-imx490-cam3
      gstreamer-options: 'video/x-raw, width=2880, height=1860, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c2-2

  test-camera-3:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-imx490-cam4
      gstreamer-options: 'video/x-raw, width=2880, height=1860, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c2-3

  test-camera-4:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-isx021-cam5
      gstreamer-options: 'video/x-raw, width=1920, height=1280, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c1-4

  test-camera-5:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-isx021-cam6
      gstreamer-options: 'video/x-raw, width=1920, height=1280, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c1-5

  test-camera-6:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-imx490-cam7
      gstreamer-options: 'video/x-raw, width=2880, height=1860, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c2-6

  test-camera-7:
    needs: camera-hotplug
    uses: ./.github/workflows/test-v4l2-gstreamer-hosted.yaml
    with:
      platform: rqx58g-c
      video-device: /dev/gmsl/tier4-imx490-cam8
      gstreamer-options: 'video/x-raw, width=2880, height=1860, framerate=30/1, format=UYVY'
      artifact-name: gstreamer-v4l2-mjpeg-c2-7

  unload-camera-drivers:
    needs: [test-camera-0, test-camera-1, test-camera-2, test-camera-3, test-camera-4, test-camera-5, test-camera-6, test-camera-7]
    uses: ./.github/workflows/unload-drivers-hosted.yaml
    with:
      platform: rqx58g-c
